# These are the default Jekyll configuration settings, which are explicit here to prevent a configuration warning when starting the Jekyll server. To change these or learn more about configuration, visit http://jekyllrb.com/docs/configuration/.

source:      .
destination: ./_site
layouts_dir:     ./_layouts
encoding:    utf-8

future:      true
show_drafts: nil
limit_posts: 0

markdown:      rdiscount

baseurl:     
url:         https://library.princeton.edu/njmaps
lsi:         false